spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password: '{cipher}c0267cd13832d97bef2548fca33f93f729ea619c807b02921fb976b21222f4d6'

token:
  expiration_time: 8640000000
  secret: user_token

gateway:
  ip: 192.168.0.3  